name:                problem5
version:             0.1.0.0
github:              "mkhan45/problem5"
license:             BSD3
author:              "Mikail Khan"
maintainer:          "mikail.khan@protonmail.com"
copyright:           "Mikail Khan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mkhan45/problem5#readme>

dependencies:
- base >= 4.7 && < 5
- hashmap

library:
  source-dirs: src

executables:
  problem5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - problem5

tests:
  problem5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - problem5
